name: Build APK Bos

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04 # <-- Ini kunci utamanya, kita turunkan ke versi server yang stabil

    steps:
    - name: Ambil Kode
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependensi Ubuntu
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install buildozer cython==0.29.33 virtualenv

    - name: Build APK
      run: |
        # Cek jika file spec belum ada, maka buat baru. Mencegah error crash.
        if [ ! -f "buildozer.spec" ]; then yes | buildozer init; fi
        buildozer -v android debug

    - name: Upload Hasil APK
      uses: actions/upload-artifact@v4
      with:
        name: Aplikasi-Bos
        path: bin/*.apk
