name: Build APK Bos

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Dependensi
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        pip3 install --user --upgrade buildozer cython virtualenv

    - name: Build APK dengan Buildozer
      run: |
        yes | buildozer init
        buildozer -v android debug

    - name: Upload Hasil APK
      uses: actions/upload-artifact@v4
      with:
        name: Aplikasi-Bos
        path: bin/*.apk
