name: Build APK Bos

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Ambil Kode
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Buildozer dan Dependensi
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        pip install --upgrade buildozer cython==0.29.33 virtualenv

    - name: Buat Buildozer Spec dan Build APK
      run: |
        yes | buildozer init
        buildozer -v android debug

    - name: Upload APK ke GitHub
      uses: actions/upload-artifact@v4
      with:
        name: Aplikasi-Bos
        path: bin/*.apk
